# Generated by Django 3.2.22 on 2023-10-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='role',
            field=models.CharField(default='employer', max_length=10),
        ),
    ]
