# Generated by Django 3.2.20 on 2023-10-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='is_posted',
        ),
        migrations.AddField(
            model_name='card',
            name='date_comment',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ПУБЛИКАЦИЯ', 'ПУБЛИКАЦИЯ'), ('РАССМОТРЕНИЕ', 'РАССМОТРЕНИЕ'), ('ДОРАБОТКА', 'ДОРАБОТКА')], default='РАССМОТРЕНИЕ', max_length=12),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date_comment',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('ПУБЛИКАЦИЯ', 'ПУБЛИКАЦИЯ'), ('ЧЕРНОВИК', 'ЧЕРНОВИК'), ('РАССМОТРЕНИЕ', 'РАССМОТРЕНИЕ'), ('ДОРАБОТКА', 'ДОРАБОТКА')], default='РАССМОТРЕНИЕ', max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='logo',
            field=models.ImageField(default='logo_images/default_logo.jpg', upload_to='logo_images'),
        ),
    ]
