# Generated by Django 4.2.6 on 2023-10-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='inn',
        ),
    ]
