# Generated by Django 3.2.22 on 2023-10-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_card_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='logo',
            field=models.ImageField(blank=True, default='logo_images/logo.jpg', null=True, upload_to='profile_images'),
        ),
    ]
