# Generated by Django 3.2.20 on 2023-11-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_chat_message'),
        ('employer', '0003_auto_20231031_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.chat'),
        ),
    ]
