# Generated by Django 3.2.22 on 2023-10-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_card_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mail',
            field=models.EmailField(max_length=100),
        ),
    ]
