# Generated by Django 4.2.6 on 2023-10-21 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_alter_resume_status'),
        ('employer', '0004_alter_card_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='logo',
            field=models.ImageField(blank=True, default='logo_images/default_logo.jpg', null=True, upload_to='profile_images'),
        ),
        migrations.CreateModel(
            name='FavoriteResumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.card')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.resume')),
            ],
        ),
    ]
