# Generated by Django 4.2.6 on 2023-10-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('skills', models.TextField(blank=True, null=True)),
                ('education', models.CharField(max_length=100)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('photo', models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images')),
                ('is_posted', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
