# Generated by Django 3.2.22 on 2023-10-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='is_posted',
            field=models.CharField(choices=[('НЕТ', 'НЕТ'), ('ДА', 'ДА')], default='НЕТ', max_length=10),
        ),
    ]
