# Generated by Django 3.2.22 on 2023-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_alter_applicant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('Муж', 'Муж'), ('Жен', 'Жен')], max_length=10),
        ),
    ]
