# Generated by Django 4.2.6 on 2023-10-26 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_initial'),
        ('applicant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.vacancy')),
            ],
        ),
    ]
