# Generated by Django 3.2.22 on 2023-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_alter_resume_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(default='Без опыта'),
        ),
    ]
