# Generated by Django 3.2.22 on 2023-10-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_resume_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='is_posted',
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('ЧЕРНОВИК', 'ЧЕРНОВИК'), ('РАССМОТРЕНИЕ', 'РАССМОТРЕНИЕ'), ('ОПУБЛИКОВАНО', 'ОПУБЛИКОВАНО'), ('ОТКЛОНЕНО', 'ОТКЛОНЕНО')], default='ЧЕРНОВИК', max_length=12),
        ),
    ]
