# Generated by Django 3.2.22 on 2023-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_auto_20231018_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('РАССМОТРЕНИЕ', 'РАССМОТРЕНИЕ'), ('ОПУБЛИКОВАНО', 'ОПУБЛИКОВАНО'), ('ОТКЛОНЕНО', 'ОТКЛОНЕНО')], default='РАССМОТРЕНИЕ', max_length=12),
        ),
    ]
